"""add visible field to widget

Revision ID: 21fdbed62863
Revises: 4fab6b791b47
Create Date: 2025-07-01 07:49:05.518715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21fdbed62863'
down_revision = '4fab6b791b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
